### ISSUE TITLE
[Bug] Connection to PDB

### ISSUE THREAD

**Issue by petrroda** [oracle/dbt-oracle#101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I can connect to a PDB but the generated models are not working due to naming issues before the dot for the create table statements. There are no issues with seeds and sources.

### Expected Behavior

-

### Steps To Reproduce

-

### Relevant log output using `--debug` flag enabled

```shell
-
```

### Environment

```markdown
- OS:Ubuntu
- Python: 3.10
- dbt: newest
```

### What Oracle database version are you using dbt with?

21 XE

### Additional Context

-

**Comment by aosingh** [comment]
Hi @petrroda 

May I know the error message you get when running dbt run ? I suspect this could be configuration issue

**Comment by aosingh** [comment]
Could you share how dbt `profiles.yml` file looks like ? It would be helpful to know the fields defined in it.

**Comment by aosingh** [comment]
@petrroda we also use XE to run dbt-oracle's CI pipeline and it works fine. Let me know if you had a chance to review the configuration

**Comment by petrroda** [comment]
I solved the issue
