### ISSUE TITLE
[Bug] DBT is trying to create table for incremental model but it exists already 

### ISSUE THREAD

**Issue by petrroda** [oracle/dbt-oracle#104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We have an incremental model and when running dbt the run fails with ORA-000955 Object with name already exists.

### Expected Behavior

DBT should see that the table already exists

### Steps To Reproduce

Can provide you our code for review

### Environment

```markdown
- OS: Windows
- Python: 3.11
- dbt: 1.6
```

**Comment by aosingh** [comment]
@petrroda 

This typically needs some configuration change. 

Could you share your quoting configurations from `dbt_project.yml` ? 

```yaml
quoting:
  database: false
  identifier: false
  schema: false
``` 

Also, is the schema returned by the following query in uppercase or lowercase ?

```sql
select SYS_CONTEXT('userenv', 'DB_NAME') FROM DUAL
```

**Comment by aosingh** [comment]
Also, the solution for issue https://github.com/oracle/dbt-oracle/issues/51 could also work here. 

I request taking a look at it.

**Comment by petrroda** [comment]
We have found the issue.
