### ISSUE TITLE
[Bug] Quoting Identifier True and Persist docs

### ISSUE THREAD

**Issue by PoleDecisionnelBAO** [oracle/dbt-oracle#130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If the Quoting Identifier parameter is set to True, column comments do not work with persist_docs

### Expected Behavior

In the file adaptaders.sql I change this line 

`        comment on column {{ relation }}.{{ column_name }} is {{ escaped_comment }}`

to 

`        comment on column {{ relation }}.{{adapter.check_and_quote_identifier(column_name, model.columns)}} is {{ escaped_comment }}`

and it works for me

### What Oracle database version are you using dbt with?

19c

**Comment by aosingh** [comment]
hi @PoleDecisionnelBAO 

Thank you for reporting the issue and also suggesting the fix. I have included the fix in the next release candidate version

```
pip install dbt-oracle==1.7.2rc1
```

Could you please test with this and let me know if it works ?

**Comment by PoleDecisionnelBAO** [comment]
yes it works. Thank

**Comment by aosingh** [comment]
`dbt-oracle==1.7.2` is released with the fix.
