### ISSUE TITLE
[Feature] Option to purge table for table materializations

### ISSUE THREAD

**Issue by espenhoh** [oracle/dbt-oracle#136]
### Describe the Feature

Currently, running table amterializations causes the recycle bin to fill up on every dbt run.
If the table was dropped with purge, it will skip the recycle bin and keep the table space clean.
It should be an option to turn purge on/off.

### Who will this benefit?

Anyone using table materializations with dbt-oracle, who also have the recycle bin activated.

**Comment by aosingh** [comment]
@espenhoh 

[dbt-oracle==1.8.3](https://pypi.org/project/dbt-oracle/1.8.3/) is released with a fix for this
