### ISSUE TITLE
[Feature] Remove dependency to Microsoft Visual C++ 14.0 

### ISSUE THREAD

**Issue by scanbix** [oracle/dbt-oracle#139]
### Describe the Feature

Hello,
I work in enterprise environment without privileged access. I can install "oracledb" package without privileged account
`python -m pip install oracledb`

However, when installing dbt-oracle, it needs Microsoft Visual C++ 14.0 and thus it needs privileged access. 
`python -m pip install dbt-oracle`

Moreover, it says  `building 'cx_Oracle' extension` - does it mean that dbt-oracle is still referencing old package, not the new one oracledb

So I don't understand, why oracledb package is installing fine, but dbt-oracle fails, even though under the hood, it fails on the same python package.

### Describe alternatives you've considered

None

### Who will this benefit?

Everyone without privileged access on Windows 11.

### Anything else?

Adding versions:
`
(dbt-env) C:\Users\BG3828\mlu_repos_personal\dbt_demo>dbt --version
Core:
 installed: 1.7.11
`

`
(dbt-env) C:\Users\BG3828\mlu_repos_personal\dbt_demo>python --version
Python 3.11.5
`

**Comment by aosingh** [comment]
@scanbix 

Originally dbt-oracle was built using `cx_Oracle`. We support both `cx_Oracle` and `oracledb` for users to be able to migrate smoothly. By default, dbt-oracle uses `oracledb`. 

We plan to remove `cx_Oracle` from dependency requirement. 

if you have `oracledb` installed try installing dbt-oracle in the following manner:

```
python -m pip install dbt-core==1.7.11
python -m pip install --no-dependencies dbt-oracle
```

This should avoid `cx_Oracle`
