### ISSUE TITLE
Release support for 1.8 on PyPI

### ISSUE THREAD

**Issue by jnoynaert** [oracle/dbt-oracle#149]
### Describe the Feature

It looks like dbt 1.8 support was merged to master but is not yet available as a release

### Describe alternatives you've considered

Install from git commit

### Who will this benefit?

Everyone!

**Comment by aosingh** [comment]
Hi @jnoynaert 

I will get it out today. I wanted to include a fix for materialized view which was merged yesterday. 

Thanks

**Comment by aosingh** [comment]
`dbt-oracle==1.8.0` is released on PyPI
