### ISSUE TITLE
[Bug] quoting database not working after upgrade to dbt-oracle >= 1.8.0

### ISSUE THREAD

**Issue by Joul1285** [oracle/dbt-oracle#153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello,
With dbt-oracle 1.7.x I was using this flag in my dbt_project.yml
```yml
quoting:
  database: false
```

However, with the release of version 1.8.x, it seems that we now need to specify the "database" value in the profiles.yml file. I have attempted to provide the value in both lowercase and uppercase, but so far, I haven't achieved the desired result.

Additionally, I have tried various combinations of quoting properties, as shown below:
```yml
quoting:
  database: false/true
  identifier: false/true
  schema: false/true
```

When attempting to build a model, DBT raised the following error:
```bash
Compilation Error in model my_model (models/my_model.sql)
  When searching for a relation, dbt found an approximate match. Instead of guessing
  which relation to use, dbt will move on. Please delete MY_SCHEMA.MY_MODEL, or rename it to be less ambiguous.
  Searched for: MY_SCHEMA.MY_MODEL
  Found: MY_SCHEMA.MY_MODEL
```
Despite this error, the model was successfully built in the database.

Furthermore, I noticed that if I do not provide the "database" value in the profiles.yml file, I receive a warning during each run, but no error on run.

Has anyone else encountered this issue? Any insights or suggestions would be greatly appreciated.

### Environment

```markdown
- dbt-core: 1.8.1
- dbt-oracle: 1.8.1
```

### What Oracle database version are you using dbt with?

19c

### Additional Context

`select SYS_CONTEXT('userenv', 'DB_NAME') from dual;`
Return my database name in lowercase.

**Comment by aosingh** [comment]
@Joul1285 

Could you enable quoting only for the `database` and let me know how it goes ?

```yaml
quoting:
  database: true
```

**Comment by Joul1285** [comment]
> @Joul1285
> 
> Could you enable quoting only for the `database` and let me know how it goes ?
> 
> ```yaml
> quoting:
>   database: true
> ```

Hello @aosingh ,

With the configuration you mentioned I still have the same warning or error messages.

If a don't reference my database target in profile.yml, I have this warning message, but no error at the end:
```
oracle adapter: [WARNING]: database key is missing from the target profile in the file profiles.yml 
 Starting with dbt-oracle 1.8  database name is needed for catalog generation
 Without database key in the target profile the generated catalog will be empty
 i.e. `dbt docs generate` command will generate an empty catalog json
 Make the following entry in dbt profile.yml file for the target profile
 database: mydatabasename
```

If a reference my database target in lowercase in profile.yml, I have this error:
```
When searching for a relation, dbt found an approximate match. Instead of guessing
  which relation to use, dbt will move on. Please delete MYSCHEMA.mymodel, or rename it to be less ambiguous.
  Searched for: MYSCHEMA.MYMODEL
  Found: MYSCHEMA.mymodel
```

Another try, if a reference my database target in uppercase in profile.yml, I have this error:
```
When searching for a relation, dbt found an approximate match. Instead of guessing
  which relation to use, dbt will move on. Please delete MYSCHEMA.MYMODEL, or rename it to be less ambiguous.
  Searched for: MYSCHEMA.MYMODEL
  Found: MYSCHEMA.MYMODEL
```

Thank you for your help.

**Comment by aosingh** [comment]
I want to confirm, have you tried the 2 together i.e. ? 

- Enable quoting only for `database`
- Reference database in lowercase in `profile.yml` ?

**Comment by Joul1285** [comment]
> @Joul1285
> 
> I want to confirm, have you tried the 2 together i.e. ?
> 
> * Enable quoting only for `database`
> * Reference database in lowercase in `profile.yml` ?

Yes I did, I have the same error as mentioned before.

**Comment by aosingh** [comment]
@Joul1285 

Could you test with the release candidate `dbt-oracle==1.8.3rc1` ?

I am unable to reproduce the problem but based on my understanding I have added a fix. To test the fix, please follow the below steps:

- Install `dbt-oracle==1.8.3rc1`
```
pip install dbt-oracle==1.8.3rc1
```

- Added database entry in `profile.yml` in lowercase

- Use quoting configuration which you had with dbt 1.7. 
```yaml
quoting:
  database: false
```
FYI - By default, quoting is disabled so you don't have to explicitly disable it. 

Let me know how this goes and we will release version 1.8.3

**Comment by Joul1285** [comment]
Hello @aosingh, 
I apologize, but I'm unable to install the release candidate in my company's environment as we only have access to an internal artifact repository. 
However, I have reviewed the changes for this release, and it appears that it could potentially resolve the issue I'm facing. I will keep you updated if I find a way to test it or once the release is available. 
Thank you for your time and assistance.

**Comment by Joul1285** [comment]
@aosingh ,
I tested version 1.8.3rc1 in my environment, and I can confirm that it fixed my problem!
I will wait for the stable release before proceeding with the upgrade.
Thank again for your time and assistance.

**Comment by aosingh** [comment]
@Joul1285 

[dbt-oracle==1.8.3](https://pypi.org/project/dbt-oracle/1.8.3/) is released
