### ISSUE TITLE
[Feature] upgrade driver from `cx_oracle` to new `oracledb` package

### ISSUE THREAD

**Issue by dataders** [oracle/dbt-oracle#17]
### Describe the Feature

I just saw on the `cx_oracle` homepage, that the package has been renamed to `oracledb` ([PyPI](https://pypi.org/project/oracledb/) | [GitHub](https://github.com/oracle/python-oracledb)) as of May 25 2022. Beyond upgrading just to say current with the newest major versions, I saw that   [oracle/python-oracledb](https://github.com/oracle/python-oracledb) (`oracledb`) has a "thin client" mode which may obviate the need for users to install drivers as came up in [Sam Fintz's issue in #db-oracle](https://getdbt.slack.com/archives/C01PWH4TXLY/p1653088000256399).

Might be worth looking into!

**Comment by aosingh** [comment]
This is now addressed in release `dbt-oracle==1.1.1`
