### ISSUE TITLE
[Feature] Docs should mention how to install Oracle client libraries

### ISSUE THREAD

**Issue by dataders** [oracle/dbt-oracle#18]
### Describe the Feature

This repo's [README.md](https://github.com/oracle/dbt-oracle/blob/main/README.md) as well as the [Oracle profile setup page on docs.getdbt.com](https://docs.getdbt.com/reference/warehouse-profiles/oracle-profile) do not mention how to install the client libraries or even link to [the standard Oracle doc on how to do so](https://www.oracle.com/database/technologies/instant-client/winx64-64-downloads.html) -- they should as its an important step that users have to take!

### Describe alternatives you've considered

If #17 , is addressed, then perhaps information will no longer be needed!

### Who will this benefit?

All new users to dbt-oracle!

**Comment by aosingh** [comment]
This is merged and dbt docs website is now live with the changes - https://docs.getdbt.com/reference/warehouse-profiles/oracle-profile
