### ISSUE TITLE
[Feature] release `dbt-oracle` `v1.1.0`?

### ISSUE THREAD

**Issue by dataders** [oracle/dbt-oracle#19]
### Describe the Feature

It'd be great to let Oracle users be able to use dbt-core 1.1.0. Additionally, it's be great as partners to be ensure that you are migrated to the unit test suite. This will be the foundation for us to ensure a good UX for end users moving forward.

**Comment by aosingh** [comment]
Hi @dataders 

I am testing this. For dbt-oracle v1.1.0 the major changes will be
- Migrating to the new testing framework introduced in dbt-core==1.1.0
- Dropping support for Python 3.6
- Adding support for Python 3.10

**Comment by aosingh** [comment]
Hi @dataders 

dbt-oracle v1.1.0 is now released - https://pypi.org/project/dbt-oracle/1.1.0/
