### ISSUE TITLE
[Feature] Consolidate docs to docs.getdbt.com side

### ISSUE THREAD

**Issue by dataders** [oracle/dbt-oracle#20]
### Describe the Feature

This repo's [README.md](https://github.com/oracle/dbt-oracle/blob/main/README.md) as well as the [Oracle profile setup page on docs.getdbt.com](https://docs.getdbt.com/reference/warehouse-profiles/oracle-profile) have significant overlap.

I propose (though open to sugggestions)
1. keeping the README to very simple. maybe even simpler than [dbt-snowflake's](https://github.com/dbt-labs/dbt-snowflake)
2. adding a "Oracle configuration" page to the docs.getdbt.com

**Comment by aosingh** [comment]
Hi @dataders 

For the upcoming release v1.0.3, this is the updated [README.md](https://github.com/oracle/dbt-oracle/blob/release/v1.0.3/README.md)

Let me know if you have any feedback
