### ISSUE TITLE
[Bug] recreating table causes ORA-00955 name is already used by an existing object

### ISSUE THREAD

**Issue by unrepeat** [oracle/dbt-oracle#49]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

if running `dbt run -m test_table` for the first time works fine. If this command is run again error is raised:
`ORA-00955: name is already used by an existing object`
Looking into log file, there are 2 SQLs executed:
`CREATE TABLE *****.test_table__dbt_tmp as SELECT.......`
`ALTER TABLE ****.test_table__dbt_tmp rename to test_table`
Error is after rename because `test_table` exists from first run, shouldn't it be dropped?

### Expected Behavior

`test_table` should be dropped before renaming.

### Environment

```markdown
- OS: Red Hat 8.5.0-3
- Python: 3.8.12
- dbt: 1.2.1
- dbt-oracle: 1.2.1
```

### What Oracle database version are you using dbt with?

12c

**Comment by aosingh** [comment]
@unrepeat 
What is the quoting configuration in `dbt-project.yml` file?

**Comment by aosingh** [comment]
It would also be good to check database name if it is lowercase or uppercase. I am suspecting there is some mismatch in the metadata which can be fixed by quoting the correct component. 

```sql
select SYS_CONTEXT('userenv', 'DB_NAME') from dual;
```

**Comment by unrepeat** [comment]
I was thinking the same about quoting and tried 3 different variations: 
quoting:
  database: true | false | false 
  schema: true | false | false
  identifier: true | false | true
but it was not it. Thank you for the `select` it actually show slitgly different name than I was having in the config. After adjusting `database` in `profiles.yml` everything is working as it should. Problem solved, thanks!
