### ISSUE TITLE
[Bug] "Compilation error" on second run. "When searching for a relation, dbt found an approximate match. Instead of guessing which relation to use, dbt will move on."

### ISSUE THREAD

**Issue by iron0012** [oracle/dbt-oracle#51]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am a beginner, trying to make a minimal working project using real data from an Oracle db that I have access to. My project consists of only a single model, which simply selects two columns from an existing table in my Oracle db. 

the model is called DBT_TEST_DM_SUBSET.sql

its contents are simply this:
`SELECT 
	MATERIAL_NUMBER_DESC,
	MATERIAL_GROUP_DESC
FROM FCDR_V6_DM_MVW`

FCDR_V6_DM_MVW is a table (actually a materialized view) in a schema called EXPLORER.

My project's name is "dan_test". When I run this at the command line:
dbt run --select dan_test

the first time everything is ok, and the view called DBT_TEST_DM_SUBSET is correctly created in my oracle db. 
The second time I run dbt run, I get this error:
<img width="1221" alt="image" src="https://user-images.githubusercontent.com/8052991/198109114-7e9d68c5-945e-4555-a84e-5a51c965eb82.png">

Using flag "--full-refresh" does not help. 
I am aware this error often has to do with lower/upper casing. However, in my profiles.yml, my schema is also all-caps: EXPLORER . The model-defining file name itself is also in all-caps: DBT_TEST_DM_SUBSET.sql

What could be causing this error? Because I am a raw beginner, I have no way of knowing if this is a bug, or if I have configured something incorrectly. 

I am on the brand-new version of dbt-oracle (1.3.0), but I also had the same problem before updating.

### Environment

```markdown
- OS: macOS 12.6
- Python: 3.8
- dbt: 1.3.0
```

### What Oracle database version are you using dbt with?

12c

**Comment by aosingh** [comment]
Thank you @iron0012 for the detailed report. I am suspecting there is some mismatch in the metadata. 

Could you let me know the following ?

- is the database name uppercase of lowercase ? You can check that by running the following query.
```sql
select SYS_CONTEXT('userenv', 'DB_NAME') from dual;
```
- Does the database name returned above match the database name which you have defined in dbt profile yml file?

-  What is the quoting configuration in dbt-project.yml file?

**Comment by iron0012** [comment]
Hello, thank you for your response.

The database name returned from the query you gave is lowercase. I have tried entering that database name in profiles.yml in lowercase, uppercase, and omitting it entirely (since it was said to be optional). I get the same error in all cases.

In dbt_project.yml, I have tried omitting a quoting configuration entirely (the default), as well as using this configuration, modeled on https://github.com/oracle/dbt-oracle/blob/main/dbt_adbs_test_project/dbt_project.yml

```
quoting:
  database: false
  identifier: false
  schema: false
```

**Comment by aosingh** [comment]
Is this an on-prem database ? 

If your database name is lowercase, use lowercase in profile.yml. Also, could you test after enabling quoting for `database` parameter in dbt_project.yml file ?

```
quoting:
  database: true
```

**Comment by iron0012** [comment]
Thank you for your suggestion to set the database quoting parameter to true, that seems to have solved the problem! I appreciate your help!

**Comment by ggam** [comment]
I was annoyed by this same problem with an on premise 11g and took a while to find this solution. Probably worth adding it as a note to the landing page of the documentation.

**Comment by aosingh** [comment]
@ggam 
I will add this to the documentation. Thanks for raising this

**Comment by ggam** [comment]
@aosingh great, thanks a lot!
