### ISSUE TITLE
[Feature] oracle__make_temp_relation identifier uniqueness improvements

### ISSUE THREAD

**Issue by nzlysenko** [oracle/dbt-oracle#55]
### Describe the Feature

Hello. At the moment temp relation unique identifier has the date string with "%H%M%S", but when we are making dbt run in parallel for the same model with incremental materialization it can cause an issue when a temporary table already exists. It's known that officially dbt doesn't support parallel runs but in some cases it may be quite useful. Is it possible to add milliseconds "%H%M%S%f" or maybe replace that identifier with something else to make it more robust?

**Comment by aosingh** [comment]
Thanks @nzlysenko for the feature request. Yes, this should be possible. Meanwhile, until the next release, you can override the macro in your dbt project. 

In your project directory, copy the following in `macros/temp_relation.sql` (You can give it any arbitrary name)

```sql
{% macro oracle__make_temp_relation(base_relation, suffix) %}
    {% set dt = modules.datetime.datetime.now() %}
    {% set dtstring = dt.strftime("%H%M%S%f") %}
    {% set tmp_identifier = 'o$pt_' ~ base_relation.identifier ~ dtstring %}
    {% set tmp_relation = base_relation.incorporate(
                                path={"identifier": tmp_identifier, "schema": None}) -%}

    {% do return(tmp_relation) %}
{% endmacro %}
```

**Comment by nzlysenko** [comment]
Got it, thank you!

**Comment by aosingh** [comment]
The macro `oracle__make_temp_relation` is updated in `dbt-core==1.3.1` to add milliseconds in the date string "%H%M%S%f"
