### ISSUE TITLE
Ephemeral materialization not working as expected

### ISSUE THREAD

**Issue by nadialloppi** [oracle/dbt-oracle#68]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Running sql query with ephemeral materialization returns nested WITH clauses.

WITH  dbt__cte__name__ as (
WITH
source AS (
    SELECT * FROM foo_schema.foo_table
),

### Expected Behavior

The expected behavior is a linear, not nested, list of CTE clauses.

### Environment

```markdown
- OS:
- Python: 3.10
- dbt: 1.3.2rc1
```

**Comment by aosingh** [comment]
@nadialloppi 

dbt's ephemeral materialization is meant to be nested

With Oracle, typically, nested WITH statements raise ` ORA-32034: unsupported use of WITH clause` You can read more about the error [here](http://www.dba-oracle.com/t_ora_32034_unsupported_use_with_clause.htm) 

To make ephemeral materialization work, one option is to remove the `WITH` keyword in the model definition. Please refer an example [epehermal model](https://github.com/oracle/dbt-oracle/blob/main/dbt_adbs_test_project/models/income_levels.sql)  which is also used in a [second model ](https://github.com/oracle/dbt-oracle/blob/main/dbt_adbs_test_project/models/us_seed_customers.sql) both included in this repository

This is the reason why [ephemeral models is not yet a supported feature](https://docs.getdbt.com/reference/warehouse-setups/oracle-setup#not-supported-features) of dbt-oracle

**Comment by aosingh** [comment]
@nadialloppi 

Did you get a chance to try the work around as shown in the example ? 
Let me know if you have any questions

Thanks
