### ISSUE TITLE
[Bug] Flaky generic tests on multiple threads

### ISSUE THREAD

**Issue by heiderich** [oracle/dbt-oracle#78]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Installing dbt-oracle 1.4.1 I suffer from https://github.com/dbt-labs/dbt-core/issues/6885 (Flaky generic tests on multiple threads), because it hardly depends on dbt-core 1.4.4.

This issue is already fixed in [dbt-core 1.4.5](https://github.com/dbt-labs/dbt-core/releases/tag/v1.4.5).

Could you bump the dependency from dbt-core from 1.4.4 to 1.4.5 (just as you did in #76)?

### Expected Behavior

generic tests work using multiple threads

### Steps To Reproduce

1. Install dbt-oracle 1.4.1 (and thus dbt-core 1.4.4).
2. Add a generic test.
3. Use multiple threads.
4. Run the tests.

(see https://github.com/dbt-labs/dbt-core/issues/6885 for details)

### Environment

```markdown
- OS: Linux
- Python: 3.8.10
- dbt: 1.4.4
```

**Comment by aosingh** [comment]
@heiderich 

I am working on [upgrading dbt-core to v1.4.5](https://github.com/oracle/dbt-oracle/blob/dev/1.4.2/setup.cfg#L36)

**Comment by aosingh** [comment]
@heiderich yes, mostly today. I will run the test suites and release it on PyPI

**Comment by aosingh** [comment]
@heiderich [1.4.2](https://pypi.org/project/dbt-oracle/) is available to install
