### ISSUE TITLE
[Bug] <DPY-6005 Database Error>

### ISSUE THREAD

**Issue by durbinar** [oracle/dbt-oracle#98]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Hi, getting the following error:
******************************************
dbt was unable to connect to the specified database.
The database returned the following error:

  >Database Error
  DPY-6005: cannot connect to database.
  timed out

*******************************************
Same error when trying different connection methods: TNS/ Using connect string /using database hostname.
no issue with hostname resolving,  any clarity and causation for this error ?, Thanks

### Environment

```markdown
- OS:Ubuntu
- Python:3.8.13
- dbt:oracle: 1.5.3
```

**Comment by aosingh** [comment]
@durbinar 

Where is this Database running ? is it on-prem or Autonomous Database ? Can you connect using SQL*PLUS  and let me know if the connection works ?

**Comment by durbinar** [comment]
@aosingh  Thanks for help, good point, sqlplus failed to connect too, then tried another oracle database (onprem) which worked fine from sqlplus, profiles.yml :
user: xxx
pass: xxx
database: xxx
schema: xxx
connection_string: jdbc:oracle:thin:@ host:PORT/ServiceID
New error:
The database returned the following error:

  >Database Error
  ORA-12154: TNS:could not resolve the connect identifier specified

Check your database credentials and try again. For more information, visit:

**Comment by aosingh** [comment]
@durbinar 

The `connection_string` seems incorrect. dbt-oracle uses the Python driver

Use any one of the following formats depending on tcp or tcps:
 - tcp://host:PORT/ServiceID

 - tcps://host:PORT/ServiceID

**Comment by durbinar** [comment]
@aosingh  perfect, it worked, could you tell what settings in oracle database may caused the earlier mentioned error# DPY-6005/timed out ?, please feel free then to close the request,  great help thanks !

**Comment by aosingh** [comment]
@durbinar Common reasons for connection timeout are:
- The Database host is not reachable from the client machine. This can be verified using `ping` or `nc` command
- if the Database host is reachable then port on which you are trying to connect might not be open

is it Autonomous Database ?
