### ISSUE TITLE
[Feature] Relax version constraint for dbt-core

### ISSUE THREAD

**Issue by nielspardon** [oracle/dbt-oracle#99]
### Describe the Feature

The version constraint for dbt-core is currently set to a specific patch release e.g. `dbt-core==1.4.6` which I find a bit too restrictive. It would make it easier to updating dbt-core without the need to wait for an update of dbt-oracle if the version constraint was relaxed a bit to allow for any patch release, e.g. `dbt-core~=1.4`.

**Comment by aosingh** [comment]
@nielspardon 

This is fixed in `dbt-oracle==1.6.0`. We will plan to backport this for v1.5 and v.1.4

**Comment by nielspardon** [comment]
awesome, thanks

**Comment by aosingh** [comment]
@nielspardon 

The fix is also backported to dbt-oracle 1.5. We have just released `dbt-oracle==1.5.3`

**Comment by aosingh** [comment]
backport released for v1.5 and v1.4
